# Preparation of Three Tank Simulation Datasets
Execute the following lines of code for the generation of the datasets. <br>
The Simulation will output a normal sequence of the tank process and different datasets including anomalies. <br>
The anomalies will be a fault in valve v12, v23, v3 and a fault in the inflow q1.<br>
How the simulation is build and which parameters are included can be read within the paper of Steude et. al (https://doi.org/10.1016/j.ifacol.2022.07.099)

In [1]:
cd ..

/home/jovyan/Discret2Di


In [2]:
from typing import Tuple

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from tqdm import tqdm

In [3]:
class ThreeTankSimulation:
    """Simulates the three tank system.
    The system is simulated using the scipy odeint function.
    """
    def __init__(self, tank_1_lvl=0, tank_2_lvl=0, tank_3_lvl=0, seed=42):
        self.tank_levels = np.array([tank_1_lvl, tank_2_lvl, tank_3_lvl])
        self.seed = seed
        self.state_df = pd.DataFrame(columns=["q1", "q3", "kv1", "kv2", "kv3", "duration"])

    def add_state(self, q1: float, q3: float, kv1: float, kv2: float, kv3: float, duration: int, name=None) -> None:
        """Add a state to the state dataframe.
        A state consists of specific settings to the system's parameters.
        Args:
            q1 (float): inflow tank 1
            q3 (float): inflow tank 3
            kv1 (float): coefficient of the valve between tank 1 and 2
            kv2 (float): coefficient of the valve between tank 2 and 3
            kv3 (float): coefficient of the outgoing valve on tank 3
            duration (int): number of time steps of the state
            name (string): the name of the state
        """
        if name is not None:
            self.state_df.loc[name] = [q1, q3, kv1, kv2, kv3, duration]
        else:
            self.state_df.append(dict(q1=q1, q3=q3, kv1=kv1, kv2=kv2, kv3=kv3, duration=duration),
                                 ignore_index=True)

    @staticmethod
    def _system_dynamics_function(x, t, q1, q3, kv1, kv2, kv3):
        # ensure non-negative tank levels
        x1, x2, x3 = x * (x > 0)
        # ODE
        dh1_dt = q1 - kv1 * np.sign(x1 - x2) * np.sqrt(np.abs(x1 - x2))
        dh2_dt = kv1 * np.sign(x1 - x2) * np.sqrt(np.abs(x1 - x2)) \
                 - kv2 * np.sign(x2 - x3) * np.sqrt(np.abs(x2 - x3))
        dh3_dt = q3 + kv2 * np.sign(x2 - x3) * np.sqrt(np.abs(x2 - x3)) - kv3 * np.sqrt(x3)

        return dh1_dt, dh2_dt, dh3_dt

    def _compute_section(self, duration: int = 10, x0: np.array = np.array([30, 10, 50]),
                         kv1: float = 1, kv2: float = 1, kv3: float = 1,
                         q1: float = 1, q3: float = 1):
        t = np.array(range(duration))
        y = odeint(self._system_dynamics_function, x0, t, (q1, q3, kv1, kv2, kv3))
        # non-negativity
        y = y * (y > 0)
        y_stop = y[-1, :]
        return y, y_stop

    @staticmethod
    def _duplicate_row(row, factor):
        return pd.concat([row.copy()] * factor, axis = 1)

    def _configuration_seq(self, cycle: list, nb_of_cycles: int,
                           sd_q: float, sd_kv: float, sd_dur: float,
                           leaky: bool, periodic_inflow: bool) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """generates configuration dataframes
        The configuration dataframe describes the state at every time step.
        Outputs original state configuration and configuration with noise.
        """
        # generate cycle of states
        seq = list()
        for i in range(nb_of_cycles):
            for state in cycle:
                if type(state) is str:
                    seq.append(self.state_df.loc[state])
                else:
                    seq.append((self.state_df.iloc[state, :]))
        seq_df = pd.concat(seq, axis=1).T.astype({"duration": int})
        seq_len = seq_df.shape[0]

        # add periodic inflow
        if periodic_inflow:
            amplitude = 0.5 * seq_df["q1"].max()
            wave = amplitude * np.cos(np.linspace(np.pi, 5*np.pi, 2000))

            q1_mask = seq_df["q1"] > 0
            q3_mask = seq_df["q3"] > 0
            
            seq_df.loc[q1_mask, "q1"] += wave[:q1_mask.sum()]
            seq_df.loc[q3_mask, "q3"] += wave[:q3_mask.sum()]

        # add noise
        np.random.seed(self.seed)
        seq_df_noise = seq_df.copy()
        if sd_q is not None:
            q_noise = np.random.normal(0, sd_q, 2 * seq_len)
            seq_df_noise["q1"] = seq_df["q1"] + q_noise[:seq_len]
            seq_df_noise["q3"] = seq_df["q3"] + q_noise[seq_len:]
            if not leaky:
                seq_df_noise["q1"].where(seq_df["q1"] > 0, other=0, inplace=True)  # no leaky inflow
                seq_df_noise["q3"].where(seq_df["q3"] > 0, other=0, inplace=True)  # (set back to 0 if no inflow)
        if sd_kv is not None:
            kv_noise = np.random.normal(0, sd_kv, 3 * seq_len)
            seq_df_noise["kv1"] = seq_df["kv1"] + kv_noise[:seq_len]
            seq_df_noise["kv2"] = seq_df["kv2"] + kv_noise[seq_len:2*seq_len]
            seq_df_noise["kv3"] = seq_df["kv3"] + kv_noise[2*seq_len:]
            if not leaky:
                seq_df_noise["kv1"].where(seq_df["kv1"] > 0, other=0, inplace=True)  # no leaky valve
                seq_df_noise["kv2"].where(seq_df["kv2"] > 0, other=0, inplace=True)
                seq_df_noise["kv3"].where(seq_df["kv3"] > 0, other=0, inplace=True)
        if sd_dur is not None:
            dur_noise = np.random.normal(0, sd_dur, seq_len)
            seq_df_noise["duration"] = round(seq_df["duration"] + dur_noise).astype(int)
        # no negative inflow etc.
        seq_df = seq_df.where(seq_df >= 0, 0)
        seq_df_noise = seq_df_noise.where(seq_df_noise >= 0, 0) 

        return seq_df, seq_df_noise

    @staticmethod
    def _export_config(seq_df, seq_df_noise, export_path):
        """exports state configuration dataframe
        Transforms the dataframe so that the state at every time step is exported.
        """
        seq0 = list()
        seq0_noise = list()
        for (_, row), (_, row_noise) in zip(seq_df.iterrows(), seq_df_noise.iterrows()):
            duration = int(row_noise.duration)  # actual duration
            seq0 += [row] * duration
            seq0_noise += [row_noise] * duration
        seq0_df = pd.concat(seq0_noise, axis=1).T
        seq0_df.to_csv(f"{export_path[:-4]}_config.csv", index=False)

    def simulate(self, cycle_list: list, nb_of_cycles_list: list,
                 sd_q: float = None, sd_kv: float = None, sd_dur: float = None, sd_white_noise: float = None, 
                 leaky: bool = False, periodic_inflow = False,
                 export_path: str = None) -> np.array:
        """Simulates the dynamics in the three-tank system
        Args:
            cycle (list): sequence of states that compose a typical cycle.
                          Either list of integers or list of state names.
            nb_of_cycles (int): number of successive cycles to simulate
            sd_q (float): if set, white noise with this standard deviation is added to the inflow
            sd_kv (float): if set, white noise with this standard deviation is added to the valve coefficients
            sd_dur (float): if set, white noise with this standard deviation is added to the duration
            leaky (bool): if true, add noise on closed valves or stopped inflow
            periodic_inflow (bool): if true, add periodic variation to the inflow
            export_path (str): if set, save simulation data at export path
        """
        seq_denoised_list = list()
        seq_list = list()
        for cycle, nb_of_cycles in zip(cycle_list, nb_of_cycles_list):
            seq_denoised, seq = self._configuration_seq(cycle, nb_of_cycles, sd_q, sd_kv, sd_dur, leaky, periodic_inflow)
            seq_denoised_list.append(seq_denoised)
            seq_list.append(seq)
        
        seq_denoised = pd.concat(seq_denoised_list, axis=0)
        seq = pd.concat(seq_list, axis=0)
        
        y_ls = []
        y_stop = self.tank_levels
        for config in tqdm(seq.itertuples(), total=len(seq)):
            y, y_stop = self._compute_section(duration=config.duration, x0=y_stop,
                                            kv1=config.kv1, kv2=config.kv2, kv3=config.kv3,
                                            q1=config.q1, q3=config.q3)
            y_ls.append(y)
        y_out = np.concatenate(y_ls)

        if sd_white_noise is not None:
            np.random.seed(self.seed)
            y_out += np.random.normal(0, sd_white_noise, y_out.shape)

        if export_path is not None:
            y_df = pd.DataFrame(y_out, columns=['h1', 'h2', 'h3'])
            y_df.to_csv(export_path, index=False)
            self._export_config(seq_denoised, seq, export_path)

        return y_out


In [4]:
tank_1_lvl=7
tank_2_lvl=3
tank_3_lvl=0
q = 0.1 # inflow
kv = 0.1 # valve coefficient
duration = 50

system = ThreeTankSimulation(tank_1_lvl=tank_1_lvl, tank_2_lvl=tank_2_lvl, tank_3_lvl=tank_3_lvl)
system.add_state(q1=q, q3=0, kv1=0,  kv2=0,  kv3=0,  duration=duration, name="q1")
system.add_state(q1=0, q3=0, kv1=kv, kv2=0,  kv3=0,  duration=duration, name="v12")
system.add_state(q1=0, q3=0, kv1=0,  kv2=kv, kv3=0,  duration=duration, name="v23")
system.add_state(q1=0, q3=0, kv1=0,  kv2=0,  kv3=kv, duration=duration, name="v3")
system.add_state(q1=0, q3=0, kv1=0,  kv2=0,  kv3=0,  duration=duration, name="rest")
system.add_state(q1=q, q3=0, kv1=0,  kv2=0,  kv3=kv, duration=duration, name="q1+v3")
system.add_state(q1=0, q3=0, kv1=kv, kv2=kv, kv3=0,  duration=duration, name="v12+v23")
system.add_state(q1=0, q3=q, kv1=0,  kv2=0,  kv3=0,  duration=duration, name="q3")

# faulty states
system.add_state(q1=0, q3=0, kv1=kv * 0.1, kv2=0,  kv3=0,  duration=duration, name="v12-faulty")
system.add_state(q1=0, q3=0, kv1=0,  kv2=kv * 0, kv3=0,  duration=duration, name="v23-faulty")
system.add_state(q1=0, q3=0, kv1=0,  kv2=0,  kv3=kv * 0.5, duration=duration, name="v3-faulty")
system.add_state(q1=1, q3=0, kv1=0,  kv2=0,  kv3=0, duration=duration, name="q1-faulty")

sd_noise = 0.1
sd_q = 0.05  # for one scenario, we add noise on the inflow
sd_dur = duration * 0.1  # for one scenario, we add noise on the duration

In [5]:
# Simulation of normal system states
system.simulate(cycle_list=[
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"]
    ],
    nb_of_cycles_list=[4, 1, 15],
    sd_q=None, sd_kv=None, sd_dur=None, sd_white_noise=sd_noise,
    periodic_inflow=False,
    export_path="preprocessed_data/tank_simulation/norm.csv"
)

100%|██████████| 140/140 [00:06<00:00, 21.98it/s]


array([[ 7.04967142,  2.98617357,  0.06476885],
       [ 7.25230299,  2.97658466, -0.0234137 ],
       [ 7.35792128,  3.07674347, -0.04694744],
       ...,
       [13.2760846 , 10.41790394,  0.82922563],
       [13.24212143, 10.33615308,  0.82147137],
       [13.43363554, 10.40107797,  0.37206751]])

In [6]:
# Simulation of an anomaly in q1 state
system.simulate(cycle_list=[
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1-faulty", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"]
    ],
    nb_of_cycles_list=[4, 1, 15],
    sd_q=None, sd_kv=None, sd_dur=None, sd_white_noise=sd_noise,
    periodic_inflow=False,
    export_path="preprocessed_data/tank_simulation/q1_faulty.csv"
)

100%|██████████| 140/140 [00:05<00:00, 27.01it/s]


array([[ 7.04967142,  2.98617357,  0.06476885],
       [ 7.25230299,  2.97658466, -0.0234137 ],
       [ 7.35792128,  3.07674347, -0.04694744],
       ...,
       [13.64128699, 10.73967233,  0.91808806],
       [13.60732381, 10.65792147,  0.90537835],
       [13.79883792, 10.72284636,  0.45101904]])

In [7]:
# Simulation of an anomaly in q1 state for 3 cycles
system.simulate(cycle_list=[
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1-faulty", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"]
    ],
    nb_of_cycles_list=[4, 3, 15],
    sd_q=None, sd_kv=None, sd_dur=None, sd_white_noise=sd_noise,
    periodic_inflow=False,
    export_path="preprocessed_data/tank_simulation/q1_faulty_3cycles.csv"
)

100%|██████████| 154/154 [00:03<00:00, 44.79it/s]


array([[ 7.04967142,  2.98617357,  0.06476885],
       [ 7.25230299,  2.97658466, -0.0234137 ],
       [ 7.35792128,  3.07674347, -0.04694744],
       ...,
       [14.83515569, 11.78820988,  1.12369527],
       [14.4620668 , 11.6197649 ,  1.02677147],
       [14.71751835, 11.67330369,  0.87716826]])

In [8]:
# Simulation of an anomaly in v12 state
system.simulate(cycle_list=[
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12-faulty", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"]
    ],
    nb_of_cycles_list=[4, 1, 15],
    sd_q=None, sd_kv=None, sd_dur=None, sd_white_noise=sd_noise,
    periodic_inflow=False,
    export_path="preprocessed_data/tank_simulation/v12_faulty.csv"
)

100%|██████████| 140/140 [00:07<00:00, 19.41it/s]


array([[ 7.04967142,  2.98617357,  0.06476885],
       [ 7.25230299,  2.97658466, -0.0234137 ],
       [ 7.35792128,  3.07674347, -0.04694744],
       ...,
       [13.28859334, 10.42890787,  0.83220544],
       [13.25463016, 10.34715702,  0.82428045],
       [13.44614427, 10.41208191,  0.37470587]])

In [9]:
# Simulation of an anomaly in v12 state
system.simulate(cycle_list=[
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12-faulty", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"]
    ],
    nb_of_cycles_list=[4, 3, 15],
    sd_q=None, sd_kv=None, sd_dur=None, sd_white_noise=sd_noise,
    periodic_inflow=False,
    export_path="preprocessed_data/tank_simulation/v12_faulty_3cycles.csv"
)

100%|██████████| 154/154 [00:06<00:00, 23.86it/s]


array([[ 7.04967142,  2.98617357,  0.06476885],
       [ 7.25230299,  2.97658466, -0.0234137 ],
       [ 7.35792128,  3.07674347, -0.04694744],
       ...,
       [13.45341076, 10.565378  ,  0.76652527],
       [13.08032186, 10.39693302,  0.6880198 ],
       [13.33577341, 10.4504718 ,  0.55683493]])

In [10]:
# Simulation of an anomaly in v23 state
system.simulate(cycle_list=[
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23-faulty", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"]
    ],
    nb_of_cycles_list=[4, 1, 15],
    sd_q=None, sd_kv=None, sd_dur=None, sd_white_noise=sd_noise,
    periodic_inflow=False,
    export_path="preprocessed_data/tank_simulation/v23_faulty.csv"
)

100%|██████████| 140/140 [00:07<00:00, 17.59it/s]


array([[ 7.04967142,  2.98617357,  0.06476885],
       [ 7.25230299,  2.97658466, -0.0234137 ],
       [ 7.35792128,  3.07674347, -0.04694744],
       ...,
       [13.29385432, 10.43353636,  0.83346009],
       [13.25989115, 10.35178551,  0.82546332],
       [13.45140526, 10.4167104 ,  0.37581695]])

In [11]:
# Simulation of an anomaly in v23 state
system.simulate(cycle_list=[
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23-faulty", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"]
    ],
    nb_of_cycles_list=[4, 3, 15],
    sd_q=None, sd_kv=None, sd_dur=None, sd_white_noise=sd_noise,
    periodic_inflow=False,
    export_path="preprocessed_data/tank_simulation/v23_faulty_3cycles.csv"
)

100%|██████████| 154/154 [00:06<00:00, 22.26it/s]


array([[ 7.04967142,  2.98617357,  0.06476885],
       [ 7.25230299,  2.97658466, -0.0234137 ],
       [ 7.35792128,  3.07674347, -0.04694744],
       ...,
       [13.46693061, 10.577276  ,  0.76976263],
       [13.09384171, 10.40883102,  0.69107289],
       [13.34929326, 10.4623698 ,  0.55970376]])

In [12]:
# Simulation of an anomaly in v3 state
system.simulate(cycle_list=[
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3-faulty"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"]
    ],
    nb_of_cycles_list=[4, 1, 15],
    sd_q=None, sd_kv=None, sd_dur=None, sd_white_noise=sd_noise,
    periodic_inflow=False,
    export_path="preprocessed_data/tank_simulation/v3_faulty.csv"
)

100%|██████████| 140/140 [00:07<00:00, 17.63it/s]


array([[ 7.04967142,  2.98617357,  0.06476885],
       [ 7.25230299,  2.97658466, -0.0234137 ],
       [ 7.35792128,  3.07674347, -0.04694744],
       ...,
       [13.29553734, 10.43501705,  0.83386162],
       [13.26157416, 10.3532662 ,  0.82584188],
       [13.45308827, 10.41819109,  0.37617256]])

In [13]:
# Simulation of an anomaly in v3 state
system.simulate(cycle_list=[
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3-faulty"],
    ["q1", "v12", "v23", "q1", "v12", "v23", "v3"]
    ],
    nb_of_cycles_list=[4, 3, 15],
    sd_q=None, sd_kv=None, sd_dur=None, sd_white_noise=sd_noise,
    periodic_inflow=False,
    export_path="preprocessed_data/tank_simulation/v3_faulty_3cycles.csv"
)

100%|██████████| 154/154 [00:07<00:00, 20.52it/s]


array([[ 7.04967142,  2.98617357,  0.06476885],
       [ 7.25230299,  2.97658466, -0.0234137 ],
       [ 7.35792128,  3.07674347, -0.04694744],
       ...,
       [13.4806755 , 10.58937338,  0.77305932],
       [13.1075866 , 10.4209284 ,  0.69418233],
       [13.36303816, 10.47446718,  0.56262595]])